// 
// Decompiled by Procyon v0.6.0
// 

public final class dxh
{
    public final int a;
    public final String b;
    public final String c;
    public final int d;
    
    public dxh(final int a, final String b, final String c) {
        this.a = a;
        this.b = b;
        this.c = c;
        final int hashCode = b.hashCode();
        int hashCode2;
        if (c == null) {
            hashCode2 = 0;
        }
        else {
            hashCode2 = c.hashCode();
        }
        this.d = hashCode * 961 + hashCode2 * 31 + a;
    }
    
    @Override
    public final boolean equals(final Object o) {
        boolean b = true;
        if (this == o) {
            return true;
        }
        if (o != null && this.getClass() == o.getClass()) {
            final dxh dxh = (dxh)o;
            if (this.a == dxh.a) {
                final String b2 = this.b;
                final String b3 = dxh.b;
                if (b2 == b3 || b2.equals(b3)) {
                    final String c = this.c;
                    final String c2 = dxh.c;
                    if (c == c2) {
                        return b;
                    }
                    if (c != null) {
                        if (c.equals(c2)) {
                            return true;
                        }
                    }
                }
            }
            b = false;
            return b;
        }
        return false;
    }
    
    @Override
    public final int hashCode() {
        return this.d;
    }
    
    @Override
    public final String toString() {
        final StringBuilder sb = new StringBuilder("TransitionId{\"");
        sb.append(this.b);
        sb.append("\", ");
        final int a = this.a;
        if (a != 1) {
            if (a != 2) {
                sb.append("AUTOGENERATED");
            }
            else {
                sb.append("SCOPED(");
                sb.append(this.c);
                sb.append(")");
            }
        }
        else {
            sb.append("GLOBAL");
        }
        sb.append("}");
        return sb.toString();
    }
}
