// 
// Decompiled by Procyon v0.6.0
// 

public enum aedb
{
    A("CONFIG_FOOTER_BUTTON_DISABLED_ALPHA", 26, "setup_compat_footer_button_disabled_alpha", 7), 
    B("CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR", 27, "setup_compat_footer_button_disabled_bg_color", 3), 
    C("CONFIG_FOOTER_PRIMARY_BUTTON_DISABLED_TEXT_COLOR", 28, "setup_compat_primary_button_disabled_text_color", 3), 
    D("CONFIG_FOOTER_SECONDARY_BUTTON_DISABLED_TEXT_COLOR", 29, "setup_compat_secondary_button_disabled_text_color", 3), 
    E("CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR", 30, "setup_compat_footer_primary_button_bg_color", 3), 
    F("CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR", 31, "setup_compat_footer_primary_button_text_color", 3), 
    G("CONFIG_FOOTER_PRIMARY_BUTTON_MARGIN_START", 32, "setup_compat_footer_primary_button_margin_start", 6), 
    H("CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR", 33, "setup_compat_footer_secondary_button_bg_color", 3), 
    I("CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR", 34, "setup_compat_footer_secondary_button_text_color", 3), 
    J("CONFIG_FOOTER_SECONDARY_BUTTON_MARGIN_START", 35, "setup_compat_footer_secondary_button_margin_start", 6), 
    K("CONFIG_LAYOUT_BACKGROUND_COLOR", 36, "setup_design_layout_bg_color", 3), 
    L("CONFIG_LAYOUT_MARGIN_START", 37, "setup_design_layout_margin_start", 6), 
    M("CONFIG_LAYOUT_MARGIN_END", 38, "setup_design_layout_margin_end", 6), 
    N("CONFIG_LAND_MIDDLE_HORIZONTAL_SPACING", 39, "setup_design_land_middle_horizontal_spacing", 6), 
    O("CONFIG_HEADER_TEXT_COLOR", 40, "setup_design_header_text_color", 3), 
    P("CONFIG_HEADER_TEXT_SIZE", 41, "setup_design_header_text_size", 6), 
    Q("CONFIG_HEADER_FONT_FAMILY", 42, "setup_design_header_font_family", 5), 
    R("CONFIG_HEADER_TEXT_MARGIN_TOP", 43, "setup_design_header_text_margin_top", 6), 
    S("CONFIG_HEADER_TEXT_MARGIN_BOTTOM", 44, "setup_design_header_text_margin_bottom", 6), 
    T("CONFIG_LAYOUT_GRAVITY", 45, "setup_design_layout_gravity", 5), 
    U("CONFIG_ICON_MARGIN_TOP", 46, "setup_design_icon_margin_top", 6), 
    V("CONFIG_ICON_SIZE", 47, "setup_design_icon_size", 6), 
    W("CONFIG_HEADER_AREA_BACKGROUND_COLOR", 48, "setup_design_header_area_background_color", 3), 
    X("CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM", 49, "setup_design_header_container_margin_bottom", 6), 
    Y("CONFIG_HEADER_AUTO_SIZE_ENABLED", 50, "setup_design_header_auto_size_enabled", 2), 
    Z("CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE", 51, "setup_design_header_auto_size_max_text_size", 6), 
    a("CONFIG_STATUS_BAR_BACKGROUND", 0, "setup_compat_status_bar_background", 4), 
    aA("CONFIG_CONTENT_INFO_PADDING_BOTTOM", 78, "setup_design_content_info_padding_bottom", 6), 
    aB("CONFIG_ITEMS_TITLE_TEXT_SIZE", 79, "setup_design_items_title_text_size", 6), 
    aC("CONFIG_ITEMS_SUMMARY_TEXT_SIZE", 80, "setup_design_items_summary_text_size", 6), 
    aD("CONFIG_ITEMS_SUMMARY_MARGIN_TOP", 81, "setup_design_items_summary_margin_top", 6), 
    aE("CONFIG_ITEMS_TITLE_FONT_FAMILY", 82, "setup_design_items_title_font_family", 5), 
    aF("CONFIG_ITEMS_SUMMARY_FONT_FAMILY", 83, "setup_design_items_summary_font_family", 5), 
    aG("CONFIG_ITEMS_PADDING_TOP", 84, "setup_design_items_padding_top", 6), 
    aH("CONFIG_ITEMS_PADDING_BOTTOM", 85, "setup_design_items_padding_bottom", 6), 
    aI("CONFIG_ITEMS_MIN_HEIGHT", 86, "setup_design_items_min_height", 6), 
    aJ("CONFIG_ITEMS_DIVIDER_SHOWN", 87, "setup_design_items_divider_shown", 2), 
    aK("CONFIG_CARD_VIEW_INTRINSIC_WIDTH", 88, "setup_design_card_view_intrinsic_width", 6), 
    aL("CONFIG_CARD_VIEW_INTRINSIC_HEIGHT", 89, "setup_design_card_view_intrinsic_height", 6), 
    aM("CONFIG_PROGRESS_ILLUSTRATION_DEFAULT", 90, "progress_illustration_custom_default", 8), 
    aN("CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT", 91, "progress_illustration_custom_account", 8), 
    aO("CONFIG_PROGRESS_ILLUSTRATION_CONNECTION", 92, "progress_illustration_custom_connection", 8), 
    aP("CONFIG_PROGRESS_ILLUSTRATION_UPDATE", 93, "progress_illustration_custom_update", 8), 
    aQ("CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD", 94, "final_hold_custom_illustration", 8), 
    aR("CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS", 95, "progress_illustration_display_minimum_ms", 1), 
    aS("CONFIG_LOADING_LOTTIE_DEFAULT", 96, "loading_animation_custom_default", 8), 
    aT("CONFIG_LOADING_LOTTIE_ACCOUNT", 97, "loading_animation_custom_account", 8), 
    aU("CONFIG_LOADING_LOTTIE_CONNECTION", 98, "loading_animation_custom_connection", 8), 
    aV("CONFIG_LOADING_LOTTIE_UPDATE", 99, "loading_animation_custom_update", 8), 
    aW("CONFIG_LOADING_LOTTIE_FINAL_HOLD", 100, "loading_animation_custom_final_hold", 8), 
    aX("CONFIG_TRANSITION_TYPE", 101, "setup_design_transition_type", 1), 
    aY("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT", 102, "loading_light_theme_customization_default", 9), 
    aZ("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT", 103, "loading_light_theme_customization_account", 9), 
    aa("CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE", 52, "setup_design_header_auto_size_min_text_size", 6), 
    ab("CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE", 53, "setup_design_header_auto_size_max_line_of_max_size", 1), 
    ac("CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA", 54, "setup_design_header_auto_size_line_spacing_extra", 6), 
    ad("CONFIG_DESCRIPTION_TEXT_SIZE", 55, "setup_design_description_text_size", 6), 
    ae("CONFIG_DESCRIPTION_TEXT_COLOR", 56, "setup_design_description_text_color", 3), 
    af("CONFIG_DESCRIPTION_LINK_TEXT_COLOR", 57, "setup_design_description_link_text_color", 3), 
    ag("CONFIG_DESCRIPTION_FONT_FAMILY", 58, "setup_design_description_font_family", 5), 
    ah("CONFIG_DESCRIPTION_LINK_FONT_FAMILY", 59, "setup_design_description_link_font_family", 5), 
    ai("CONFIG_DESCRIPTION_TEXT_MARGIN_TOP", 60, "setup_design_description_text_margin_top", 6), 
    aj("CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM", 61, "setup_design_description_text_margin_bottom", 6), 
    ak("CONFIG_ACCOUNT_NAME_TEXT_SIZE", 62, "setup_design_account_name_text_size", 6), 
    al("CONFIG_ACCOUNT_NAME_FONT_FAMILY", 63, "setup_design_account_name_font_family", 5), 
    am("CONFIG_ACCOUNT_AVATAR_MARGIN_END", 64, "setup_design_account_avatar_margin_end", 6), 
    an("CONFIG_ACCOUNT_AVATAR_SIZE", 65, "setup_design_account_avatar_size", 6), 
    ao("CONFIG_CONTENT_TEXT_SIZE", 66, "setup_design_content_text_size", 6), 
    ap("CONFIG_CONTENT_TEXT_COLOR", 67, "setup_design_content_text_color", 3), 
    aq("CONFIG_CONTENT_LINK_TEXT_COLOR", 68, "setup_design_content_link_text_color", 3), 
    ar("CONFIG_CONTENT_FONT_FAMILY", 69, "setup_design_content_font_family", 5), 
    as("CONFIG_CONTENT_LAYOUT_GRAVITY", 70, "setup_design_content_layout_gravity", 5), 
    at("CONFIG_CONTENT_PADDING_TOP", 71, "setup_design_content_padding_top", 6), 
    au("CONFIG_CONTENT_INFO_TEXT_SIZE", 72, "setup_design_content_info_text_size", 6), 
    av("CONFIG_CONTENT_INFO_FONT_FAMILY", 73, "setup_design_content_info_font_family", 5), 
    aw("CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA", 74, "setup_design_content_info_line_spacing_extra", 6), 
    ax("CONFIG_CONTENT_INFO_ICON_SIZE", 75, "setup_design_content_info_icon_size", 6), 
    ay("CONFIG_CONTENT_INFO_ICON_MARGIN_END", 76, "setup_design_content_info_icon_margin_end", 6), 
    az("CONFIG_CONTENT_INFO_PADDING_TOP", 77, "setup_design_content_info_padding_top", 6), 
    b("CONFIG_LIGHT_STATUS_BAR", 1, "setup_compat_light_status_bar", 2), 
    ba("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION", 104, "loading_light_theme_customization_connection", 9), 
    bb("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE", 105, "loading_light_theme_customization_update", 9), 
    bc("CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD", 106, "loading_light_theme_customization_final_hold", 9), 
    bd("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT", 107, "loading_dark_theme_customization_default", 9), 
    be("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT", 108, "loading_dark_theme_customization_account", 9), 
    bf("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION", 109, "loading_dark_theme_customization_connection", 9), 
    bg("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE", 110, "loading_dark_theme_customization_update", 9), 
    bh("CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD", 111, "loading_dark_theme_customization_final_hold", 9), 
    bi("CONFIG_LOADING_LAYOUT_PADDING_TOP", 112, "loading_layout_content_padding_top", 6), 
    bj("CONFIG_LOADING_LAYOUT_PADDING_START", 113, "loading_layout_content_padding_start", 6), 
    bk("CONFIG_LOADING_LAYOUT_PADDING_END", 114, "loading_layout_content_padding_end", 6), 
    bl("CONFIG_LOADING_LAYOUT_PADDING_BOTTOM", 115, "loading_layout_content_padding_bottom", 6), 
    bm("CONFIG_LOADING_LAYOUT_HEADER_HEIGHT", 116, "loading_layout_header_height", 6), 
    bn("CONFIG_LOADING_LAYOUT_FULL_SCREEN_ILLUSTRATION_ENABLED", 117, "loading_layout_full_screen_illustration_enabled", 2), 
    bo("CONFIG_LOADING_LAYOUT_WAIT_FOR_ANIMATION_FINISHED", 118, "loading_layout_wait_for_animation_finished", 2), 
    bp("CONFIG_PROGRESS_BAR_MARGIN_TOP", 119, "setup_design_progress_bar_margin_top", 6), 
    bq("CONFIG_PROGRESS_BAR_MARGIN_BOTTOM", 120, "setup_design_progress_bar_margin_bottom", 6), 
    c("CONFIG_NAVIGATION_BAR_BG_COLOR", 2, "setup_compat_navigation_bar_bg_color", 3), 
    d("CONFIG_NAVIGATION_BAR_DIVIDER_COLOR", 3, "setup_compat_navigation_bar_divider_color", 3), 
    e("CONFIG_FOOTER_BAR_BG_COLOR", 4, "setup_compat_footer_bar_bg_color", 3), 
    f("CONFIG_FOOTER_BAR_MIN_HEIGHT", 5, "setup_compat_footer_bar_min_height", 6), 
    g("CONFIG_FOOTER_BAR_PADDING_START", 6, "setup_compat_footer_bar_padding_start", 6), 
    h("CONFIG_FOOTER_BAR_PADDING_END", 7, "setup_compat_footer_bar_padding_end", 6), 
    i("CONFIG_LIGHT_NAVIGATION_BAR", 8, "setup_compat_light_navigation_bar", 2), 
    j("CONFIG_FOOTER_BUTTON_FONT_FAMILY", 9, "setup_compat_footer_button_font_family", 5), 
    k("CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER", 10, "setup_compat_footer_button_icon_add_another", 4), 
    l("CONFIG_FOOTER_BUTTON_ICON_CANCEL", 11, "setup_compat_footer_button_icon_cancel", 4), 
    m("CONFIG_FOOTER_BUTTON_ICON_CLEAR", 12, "setup_compat_footer_button_icon_clear", 4), 
    n("CONFIG_FOOTER_BUTTON_ICON_DONE", 13, "setup_compat_footer_button_icon_done", 4), 
    o("CONFIG_FOOTER_BUTTON_ICON_NEXT", 14, "setup_compat_footer_button_icon_next", 4), 
    p("CONFIG_FOOTER_BUTTON_ICON_OPT_IN", 15, "setup_compat_footer_button_icon_opt_in", 4), 
    q("CONFIG_FOOTER_BUTTON_ICON_SKIP", 16, "setup_compat_footer_button_icon_skip", 4), 
    r("CONFIG_FOOTER_BUTTON_ICON_STOP", 17, "setup_compat_footer_button_icon_stop", 4), 
    s("CONFIG_FOOTER_BUTTON_PADDING_TOP", 18, "setup_compat_footer_button_padding_top", 6), 
    t("CONFIG_FOOTER_BUTTON_PADDING_BOTTOM", 19, "setup_compat_footer_button_padding_bottom", 6), 
    u("CONFIG_FOOTER_BUTTON_RADIUS", 20, "setup_compat_footer_button_radius", 6), 
    v("CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA", 21, "setup_compat_footer_button_ripple_alpha", 7), 
    w("CONFIG_FOOTER_BUTTON_TEXT_SIZE", 22, "setup_compat_footer_button_text_size", 6), 
    x("CONFIG_FOOTER_BUTTON_TEXT_STYLE", 23, "setup_compat_footer_button_text_style", 1), 
    y("CONFIG_FOOTER_BUTTON_MIN_HEIGHT", 24, "setup_compat_footer_button_min_height", 6), 
    z("CONFIG_FOOTER_BUTTON_ALIGNED_END", 25, "setup_compat_footer_button_aligned_end", 2);
    
    public final String br;
    public final int bs;
    
    private aedb(final String s, final int n, final String br, final int bs) {
        this.br = br;
        this.bs = bs;
    }
}
