import java.util.HashMap;

// 
// Decompiled by Procyon v0.6.0
// 

final class aqtb
{
    static final HashMap a;
    static final HashMap b;
    private static final int[] e;
    private static final int[] f;
    private static final int[] g;
    private static final int[] h;
    private static final int[] i;
    private static final int[] j;
    private static final int[] k;
    private static final int[] l;
    private static final int[] m;
    private static final int[] n;
    private static final int[] o;
    private static final int[] p;
    private static final int[] q;
    private static final int[] r;
    private static final int[] s;
    private static final int[] t;
    private static final int[] u;
    final int c;
    final int[] d;
    
    static {
        final int[] array;
        final int[] e2 = array = new int[2];
        array[0] = 48;
        array[1] = 57;
        e = e2;
        final int[] array2;
        final int[] f2 = array2 = new int[6];
        array2[0] = 9;
        array2[1] = 10;
        array2[2] = 12;
        array2[3] = 13;
        array2[5] = (array2[4] = 32);
        f = f2;
        final int[] array3;
        final int[] g2 = array3 = new int[8];
        array3[0] = 48;
        array3[1] = 57;
        array3[2] = 65;
        array3[3] = 90;
        array3[5] = (array3[4] = 95);
        array3[6] = 97;
        array3[7] = 122;
        g = g2;
        final HashMap a2 = new HashMap();
        (a = a2).put("\\d", new aqtb(1, e2));
        a2.put("\\D", new aqtb(-1, e2));
        a2.put("\\s", new aqtb(1, f2));
        a2.put("\\S", new aqtb(-1, f2));
        a2.put("\\w", new aqtb(1, g2));
        a2.put("\\W", new aqtb(-1, g2));
        final int[] array4;
        final int[] h2 = array4 = new int[6];
        array4[0] = 48;
        array4[1] = 57;
        array4[2] = 65;
        array4[3] = 90;
        array4[4] = 97;
        array4[5] = 122;
        h = h2;
        final int[] array5;
        final int[] i2 = array5 = new int[4];
        array5[0] = 65;
        array5[1] = 90;
        array5[2] = 97;
        array5[3] = 122;
        i = i2;
        final int[] array6;
        final int[] j2 = array6 = new int[2];
        array6[0] = 0;
        array6[1] = 127;
        j = j2;
        final int[] array7;
        final int[] k2 = array7 = new int[4];
        array7[1] = (array7[0] = 9);
        array7[3] = (array7[2] = 32);
        k = k2;
        final int[] array8;
        final int[] l2 = array8 = new int[4];
        array8[0] = 0;
        array8[1] = 31;
        array8[3] = (array8[2] = 127);
        l = l2;
        final int[] array9;
        final int[] m2 = array9 = new int[2];
        array9[0] = 48;
        array9[1] = 57;
        m = m2;
        final int[] array10;
        final int[] n2 = array10 = new int[2];
        array10[0] = 33;
        array10[1] = 126;
        n = n2;
        final int[] array11;
        final int[] o2 = array11 = new int[2];
        array11[0] = 97;
        array11[1] = 122;
        o = o2;
        final int[] array12;
        final int[] p2 = array12 = new int[2];
        array12[0] = 32;
        array12[1] = 126;
        p = p2;
        final int[] array13;
        final int[] q2 = array13 = new int[8];
        array13[0] = 33;
        array13[1] = 47;
        array13[2] = 58;
        array13[3] = 64;
        array13[4] = 91;
        array13[5] = 96;
        array13[6] = 123;
        array13[7] = 126;
        q = q2;
        final int[] array14;
        final int[] r2 = array14 = new int[4];
        array14[0] = 9;
        array14[1] = 13;
        array14[3] = (array14[2] = 32);
        r = r2;
        final int[] array15;
        final int[] s2 = array15 = new int[2];
        array15[0] = 65;
        array15[1] = 90;
        s = s2;
        final int[] array16;
        final int[] t2 = array16 = new int[8];
        array16[0] = 48;
        array16[1] = 57;
        array16[2] = 65;
        array16[3] = 90;
        array16[5] = (array16[4] = 95);
        array16[6] = 97;
        array16[7] = 122;
        t = t2;
        final int[] array17;
        final int[] u2 = array17 = new int[6];
        array17[0] = 48;
        array17[1] = 57;
        array17[2] = 65;
        array17[3] = 70;
        array17[4] = 97;
        array17[5] = 102;
        u = u2;
        final HashMap b2 = new HashMap();
        (b = b2).put("[:alnum:]", new aqtb(1, h2));
        b2.put("[:^alnum:]", new aqtb(-1, h2));
        b2.put("[:alpha:]", new aqtb(1, i2));
        b2.put("[:^alpha:]", new aqtb(-1, i2));
        b2.put("[:ascii:]", new aqtb(1, j2));
        b2.put("[:^ascii:]", new aqtb(-1, j2));
        b2.put("[:blank:]", new aqtb(1, k2));
        b2.put("[:^blank:]", new aqtb(-1, k2));
        b2.put("[:cntrl:]", new aqtb(1, l2));
        b2.put("[:^cntrl:]", new aqtb(-1, l2));
        b2.put("[:digit:]", new aqtb(1, m2));
        b2.put("[:^digit:]", new aqtb(-1, m2));
        b2.put("[:graph:]", new aqtb(1, n2));
        b2.put("[:^graph:]", new aqtb(-1, n2));
        b2.put("[:lower:]", new aqtb(1, o2));
        b2.put("[:^lower:]", new aqtb(-1, o2));
        b2.put("[:print:]", new aqtb(1, p2));
        b2.put("[:^print:]", new aqtb(-1, p2));
        b2.put("[:punct:]", new aqtb(1, q2));
        b2.put("[:^punct:]", new aqtb(-1, q2));
        b2.put("[:space:]", new aqtb(1, r2));
        b2.put("[:^space:]", new aqtb(-1, r2));
        b2.put("[:upper:]", new aqtb(1, s2));
        b2.put("[:^upper:]", new aqtb(-1, s2));
        b2.put("[:word:]", new aqtb(1, t2));
        b2.put("[:^word:]", new aqtb(-1, t2));
        b2.put("[:xdigit:]", new aqtb(1, u2));
        b2.put("[:^xdigit:]", new aqtb(-1, u2));
    }
    
    private aqtb(final int c, final int[] d) {
        this.c = c;
        this.d = d;
    }
}
