// 
// Decompiled by Procyon v0.6.0
// 

package com.google.android.libraries.elements.interfaces;

public enum PerformanceSpanType
{
    private static final PerformanceSpanType[] $VALUES;
    
    ASYNC_ENTER_HIERARCHY("ASYNC_ENTER_HIERARCHY", 12), 
    ASYNC_ROOT_CREATION("ASYNC_ROOT_CREATION", 11), 
    COMMAND_EXECUTION("COMMAND_EXECUTION", 3), 
    COMPONENT_MATERIALIZATION("COMPONENT_MATERIALIZATION", 1), 
    FIRST_ROOT_MATERIALIZATION("FIRST_ROOT_MATERIALIZATION", 9), 
    FIRST_ROOT_MEASUREMENT("FIRST_ROOT_MEASUREMENT", 8), 
    FIRST_ROOT_PREPARATION("FIRST_ROOT_PREPARATION", 10), 
    JAVASCRIPT_COMMAND("JAVASCRIPT_COMMAND", 17), 
    JAVASCRIPT_CONTEXT_INITIALIZATION("JAVASCRIPT_CONTEXT_INITIALIZATION", 23), 
    JAVASCRIPT_EXECUTION("JAVASCRIPT_EXECUTION", 20), 
    JAVASCRIPT_FFI_FUNCTION("JAVASCRIPT_FFI_FUNCTION", 18), 
    JAVASCRIPT_FUNCTION_BINDING("JAVASCRIPT_FUNCTION_BINDING", 25), 
    JAVASCRIPT_FUNCTION_EXECUTION("JAVASCRIPT_FUNCTION_EXECUTION", 24), 
    JAVASCRIPT_MODULE_LOADING("JAVASCRIPT_MODULE_LOADING", 22), 
    JAVASCRIPT_MODULE_PROCESSING("JAVASCRIPT_MODULE_PROCESSING", 21), 
    JAVASCRIPT_SCHEDULING("JAVASCRIPT_SCHEDULING", 19), 
    MODEL_SYNTHESIS("MODEL_SYNTHESIS", 0), 
    NATIVE_LIB_CHECKING("NATIVE_LIB_CHECKING", 16), 
    NATIVE_LIB_LOADING("NATIVE_LIB_LOADING", 15), 
    PB_TO_FB("PB_TO_FB", 14), 
    ROOT_MATERIALIZATION("ROOT_MATERIALIZATION", 6), 
    ROOT_MEASUREMENT("ROOT_MEASUREMENT", 5), 
    ROOT_MOUNTING("ROOT_MOUNTING", 4), 
    ROOT_PREPARATION("ROOT_PREPARATION", 7), 
    TEMPLATE_FETCHING("TEMPLATE_FETCHING", 13), 
    TEMPLATE_RESOLUTION("TEMPLATE_RESOLUTION", 2), 
    UNKNOWN("UNKNOWN", 26);
    
    private static PerformanceSpanType[] $values() {
        return new PerformanceSpanType[] { PerformanceSpanType.MODEL_SYNTHESIS, PerformanceSpanType.COMPONENT_MATERIALIZATION, PerformanceSpanType.TEMPLATE_RESOLUTION, PerformanceSpanType.COMMAND_EXECUTION, PerformanceSpanType.ROOT_MOUNTING, PerformanceSpanType.ROOT_MEASUREMENT, PerformanceSpanType.ROOT_MATERIALIZATION, PerformanceSpanType.ROOT_PREPARATION, PerformanceSpanType.FIRST_ROOT_MEASUREMENT, PerformanceSpanType.FIRST_ROOT_MATERIALIZATION, PerformanceSpanType.FIRST_ROOT_PREPARATION, PerformanceSpanType.ASYNC_ROOT_CREATION, PerformanceSpanType.ASYNC_ENTER_HIERARCHY, PerformanceSpanType.TEMPLATE_FETCHING, PerformanceSpanType.PB_TO_FB, PerformanceSpanType.NATIVE_LIB_LOADING, PerformanceSpanType.NATIVE_LIB_CHECKING, PerformanceSpanType.JAVASCRIPT_COMMAND, PerformanceSpanType.JAVASCRIPT_FFI_FUNCTION, PerformanceSpanType.JAVASCRIPT_SCHEDULING, PerformanceSpanType.JAVASCRIPT_EXECUTION, PerformanceSpanType.JAVASCRIPT_MODULE_PROCESSING, PerformanceSpanType.JAVASCRIPT_MODULE_LOADING, PerformanceSpanType.JAVASCRIPT_CONTEXT_INITIALIZATION, PerformanceSpanType.JAVASCRIPT_FUNCTION_EXECUTION, PerformanceSpanType.JAVASCRIPT_FUNCTION_BINDING, PerformanceSpanType.UNKNOWN };
    }
    
    static {
        $VALUES = $values();
    }
    
    private PerformanceSpanType(final String s, final int n) {
    }
}
